DataBiosphere/xsamtools

- Makefile
- setup.py
This should increase the probability of a succesful installation
> Perform ./configure during htslib build

- xsamtools/samtools.py
Use warnings if htslib/bcftools installation cannot be found.
> Improve htslib/bcftools binary discovery

- Makefile
This prevents rebuilds of samtools libraries every time tests are run.
> Update Makefile to improve test performance

- xsamtools/pipes.py
This allows a smoother shutdown of the FIFO writer if the reader shuts down early.
> Use mpu queue for safer reader exit

- xsamtools/pipes.py
This adds quick exit on forked process exceptions, and graceful error reporting.
depends on #34
> Use ProcessPoolExecutor for process concurrency

- tests/test_xsamtools.py
- xsamtools/pipes.py
Named pipes can block when the other end is not opened correctly.
For discussion, see:
https://stackoverflow.com/questions/5782279/why-does-a-read-only-open-of-a-named-pipe-block
> Readable/writable handles avoiding FIFO deadlock

- xsamtools/vcf.py
> Add convenience stubbed object

- tests/test_xsamtools.py
- xsamtools/pipes.py
- xsamtools/vcf.py
This may allow for cleaner shutdown of processes.
> Share a process executor among all pipes

- Dockerfile
`make image` should work now.  Sorry for breaking this!
> Update with samtools docker dep.

- common.mk
This snippet is unlikely to work, and trying it out would break things.
> Remove release undo recipe from Makefile

- Makefile
- common.mk
This will be useful for versioning docker images.
> Move docker recipes into common.mk

- common.mk
- environment
This will work better with dockerfile versioning
> XSAMTOOLS_IMAGE_NAME -> XSAMTOOLS_IMAGE_BASE_NAME

- common.mk
> Use version tag in Docker makefile recipes

- docker_scripts/login
This updates the docker login script with the new image naming scheme.
depends on #55 #56
> Update docker login script

- tests/test_xsamtools.py
- xsamtools/gs_utils.py
- xsamtools/vcf.py
> Perform access checks before opening FIFO pipes

- tests/test_xsamtools.py
- xsamtools/pipes.py
This class is intended to help manage the complexity and potential deadlocks involved in setting up FIFO pipes.
> Introduce FIFO Pipe base class

- tests/test_gs_utils.py
- tests/test_pipes.py
- tests/test_xsamtools.py
> Split tests into separate files

- tests/test_pipes.py
- xsamtools/pipes.py
> Blob reader uses FIFO base class

- tests/test_pipes.py
- xsamtools/pipes.py
> Blob writer uses FIFO base class

- tests/test_cram.py
This should allow `make lint` to pass again now.
> Fix linting.

- tests/test_cram.py
- xsamtools/cram.py
ITF8 is a compressed data type in CRAM that represents a 32-bit unsigned integer.
See: https://samtools.github.io/hts-specs/CRAMv3.pdf
> Add functions to encode and decode itf8.

- tests/test_cram.py
- xsamtools/cram.py
I'd like to refactor to move these cram parsing functions and the rest into their own cram parser file after this.
> Add LFT8 decode/encode.
